### ISSUE TITLE
not playing sound for awakener's orb drops

### ISSUE THREAD

**Issue by oisterjosh** [EwwItsMike/ImaDrum-Money#1]
not sure if it affects all bosses, or if it was manually added due to spam at new DT2 bosses, but plugin is not playing sound when an awakener's orb drops for me at leviathan

**Comment by EwwItsMike** [comment]
Hey, thanks for reporting this!
I suspect this might be a wider issue within RuneLite, as some Loot tracker plugins don't see any loot dropped by Leviathan (or Whisperer) either. It could be that the client itself doesn't send the message for the onLootReceived event...

But I'm getting ahead of myself. I'll look into it, thanks again!

**Comment by oisterjosh** [comment]
Just checked my loot trackers (both Loot Tracker and Loot Logger) and 11 out of my 95 kills showed up with loot. Definitely something funky going on with that. None of my awakener's orbs showed up, so your hypothesis tracks.

**Comment by EwwItsMike** [comment]
It appears that Leviathan loot was indeed not tracked correctly, which was fixed in this commit to the RuneLite client: https://github.com/runelite/runelite/commit/9113feeb0e97b4056cdda9b168f6fba399d1db9a

I have yet to do any testing myself due to IRL intervening, but I hope this has fixed the issue! If not, I'd love to hear it (cuz that would mean I missed up somewhere and need to fix it....)

**Comment by EwwItsMike** [comment]
Tested out 2 kills at Leviathan earlier today before the update, and the plugin did not play a sound. After the game update, and RuneLite update with it, I did another kill and the plugin did play a sound. 

I feel it's safe to assume the plugin will proc correctly now on every drop where it should. Thanks again for the report, and feel free to let me know if there's other issues!
